### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by NiklasPhabian**
This restructures the project. 
- We move from a single-module project to a single-package project. 
- All swigged functions end up in pystare.core.py and are private to the package. 
- Functions are exposed through pystare.spatial.py and pystare.temporal.py
- All functions are aimed to have [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html)-style docstrings. Sphinx is just as happy with RST though.
- All docstrings are aimed to include examples that will be executable through doctest
- tests are now based on pytest. Pytest can execute the legacy unittests that we have in tests/ . However, we can now also write (much simpler) pytest-style tests
- We stick to PEP8
- examples/ contains notebooks holding examples. Tests are in tests/

### CODE REVIEW

**Comment by michaelleerilee** [comment]
Is this passing all tests?

**Comment by NiklasPhabian** [comment]
> Is this passing all tests?

Yes. Btw, we can now simply call ```pytest``` in the project root. It will call the tests in tets/ and all the doctests.

```shell
======================================================== test session starts ========================================================
platform linux -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/griessbaum/Dropbox/UCSB/STARE_Project/pystare, configfile: pytest.ini
collected 81 items                                                                                                                  

pystare/spatial.py .............s                                                                                             [ 17%]
pystare/temporal.py ......................                                                                                    [ 44%]
tests/test_intersect_single_res.py .                                                                                          [ 45%]
tests/test_intersections.py ........                                                                                          [ 55%]
tests/test_spatial.py ..................                                                                                      [ 77%]
tests/test_srange.py .......                                                                                                  [ 86%]
tests/test_temporal.py ..........                                                                                             [ 98%]
tests/test_temporal_tai.py .                                                                                                  [100%]

============================================= 80 passed, 1 skipped in 67.67s (0:01:07) ==============================================
```

**Review by michaelleerilee — APPROVED** [review]
It will be interesting to see the knock-on effects to STARE-Cookbooks and pystareplotlib.

**Comment by NiklasPhabian** [comment]
> It will be interesting to see the knock-on effects to STARE-Cookbooks and pystareplotlib.

"interesting" indeed. Yes, some renamed functions and none of the private functions being exposed.

**Pull request merged**
