### PR TITLE
Temporal

### PR DESCRIPTION
**Pull request by michaelleerilee**
Add a suite of temporal capabilities.

### CODE REVIEW

**Comment by michaelleerilee** [comment]
Need to update STARE first.

**Comment by michaelleerilee** [comment]
STARE 1.0.0-beta has been released, so pystare can now pull from STARE's master branch.

**Comment by michaelleerilee** [comment]
STARE 1.2.0 has been released with from<...> calls that include resolution parameters. We don't need to execute separate calls to set resolutions now. Before the from<...> calls were considered low level constructor aids.

**Review by NiklasPhabian — APPROVED** [review]
everything works as expected (and tests pass), however, we have to address issue 39 through 47 in a refactoring effort

**Comment by NiklasPhabian** [comment]
@michaelleerilee do we delete the temporal branch now?

**Comment by michaelleerilee** [comment]
We can delete the `temporal` branch.

**Pull request merged**
